apiVersion: v1
kind: ServiceAccount
metadata:
  name: beaconsimulatordt-second
---
apiVersion: v1
kind: Service
metadata:
  name: beaconsimulatordt-second
  labels:
    app: beaconsimulatordt-second
spec:
  ports:
  - port: 4020
    targetPort: 4020
    name: http
    protocol: TCP
  - port: 7400
    targetPort: 7400
    name: dds1
    protocol: UDP
  - port: 7411
    targetPort: 7411
    name: dds2
    protocol: UDP
  selector:
    app: beaconsimulatordt-second
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beaconsimulatordt-second-v1
  labels:
    version: v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beaconsimulatordt-second
  template:
    metadata:
      labels:
        app: beaconsimulatordt-second
        version: v1
      annotations:  
        consul.hashicorp.com/connect-inject: 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'beaconsimulatordt:9998:dc2'
    spec:
      containers:
      - name: postgres
        image: fosterACR.azurecr.io/apimpostgres:4.0.0
        resources:
          requests:
            cpu: "10m"
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        envFrom:
            - configMapRef:
                name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres
      - name: fostercoresecond
        image: fosterACR.azurecr.io/foster:4.0
        env:
        - name: FOSTER_SERVICE
          value: ""
        - name: FOSTER_PORT
          value: "4020"
        - name: FOSTER_CLOUD_GW
          value: "http://127.0.0.1:9998"
        - name: FOSTER_APIM
          value: "https://preprodapim.umbrellaiot.com:9443"
        - name: FOSTER_TOKEN
          value: "<APPTOKEN>"
        - name: FOSTER_STORAGE
          value: "true"
        - name: FOSTER_PREFIX
          value: "%"
        - name: FOSTER_RESYNC
          value: "https://preprodapim.umbrellaiot.com:9096"
        - name: FOSTER_DUPLICATE
          value: "true"
        imagePullPolicy: Always
        ports:
        - containerPort: 4020
        resources:
          requests:
            cpu: "10m"
      imagePullSecrets:
        - name: foster
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      hostAliases:
       - ip: 127.0.0.1
         hostnames:
           - foster
